
[general]
import = [
  "/Users/drew/.local/share/mise/installs/node/22.5.1/lib/node_modules/alacritty-themes/themes/Argonaut.toml"
]

[env]
TERM = "xterm-256color"

[window]
decorations = "buttonless"

  [window.padding]
  x = 25
  y = 20

[font]
size = 12

  [font.bold]
  family = "JetBrainsMono Nerd Font"
  style = "Heavy"

  [font.bold_italic]
  family = "JetBrainsMono Nerd Font"
  style = "Heavy Italic"

  [font.italic]
  family = "JetBrainsMono Nerd Font"
  style = "Medium Italic"

  [font.normal]
  family = "JetBrainsMono Nerd Font"
  style = "Medium"
