name: config
root: ~/.config
windows:
  - config:
      layout: <%= ENV["MUX_LAYOUT"] %>
      panes:
        - editor:
            - fish
            - cls
            - nvim
        - cmd:
            - fish
            - cls
