name: openapi-generator-testing
root: <%= ENV["PROJECTS_DIR"] %>/openapi-generator-testing
windows:
  - root:
      layout: <%= ENV["MUX_LAYOUT"] %>
      panes:
        - editor:
            - fish
            - cls
            - nvim
        - dev:
            - fish
            - cls
        - cmd:
            - fish
            - cls
