# Generic tmuxinator config for creating throwaway tmux sessions using a pre-configured layout
# https://github.com/tmuxinator/tmuxinator?tab=readme-ov-file#erb

# Start usage: 
# mux project -n ublock d=uBlock

# Attach usage:
# tmux attach -t uBlock

# Stop usage:
# tmux kill-session -t uBlock

# NOTE: Assuming ~/projects/uBlock exists
name: project
root: ~/projects/<%= @settings["d"] %>
attach: false
windows:
  - 1)editor:
      layout: main-horizontal
      panes:
        - editor:
            - fish
            - cls
            - nvim
        - cmd1:
            - fish
            - cls
        - cmd2:
            - fish
            - cls
  - 2)stack:
      layout: main-horizontal
      panes:
        - stack:
            - fish
            - cls
