#!/usr/bin/env bash
###############################################################################
# .nbrc
#
# Configuration file for `nb`, a command line note-taking, bookmarking,
# and knowledge base application with encryption, search, Git-backed syncing,
# and more in a single portable script.
#
# Edit this file manually or manage settings using the `nb settings`
# subcommand. Configuration options are set as environment variables, eg:
#   export NB_ENCRYPTION_TOOL=gpg
#
# https://github.com/xwmx/nb
###############################################################################

export NB_ENCRYPTION_TOOL="${NB_ENCRYPTION_TOOL:-openssl}" # Set by `nb` • Sun Jun  8 05:54:16 PM CDT 2025

export NB_DEFAULT_EXTENSION="${NB_DEFAULT_EXTENSION:-norg}" # Set by `nb` • Sun Jun  8 08:24:10 PM CDT 2025
