name: database
root: <%= ENV["PROJECTS_DIR"] %>/engage/packages/database
on_project_exit: clear

windows:
  - database:
      layout: <%= ENV["MUX_LAYOUT"] %>
      panes:
        - editor:
          - <%= ENV["MUXLSHELL_RUN_CMD"] %>
          - fish
          - cls
        - devserver:
          - fish
          - cls
        - cmd:
          - <%= ENV["MUXLSHELL_RUN_CMD"] %>
          - fish
          - cls
