# Common to C and C++
CompileFlags:
  Add:
    - -pedantic
    - -Wall
    - -Weffc++
    - -Wextra
    - -Wconversion 
    - -Wsign-conversion
    - -ggdb
---
# Specific to C++
If:
  PathExclude:
    - .*\.c
    - .*\.h
CompileFlags:
  Add:
      - -std=c++23
