# this is a template for how ~/.config/mise/config.local.toml should look
[env]
GITHUB_OAUTH_TOKEN=''
# <github-username:github-oauth-token>
BUNDLE_GEMS__GITHUB__COM=""
# <github-username:github-oauth-token>
BUNDLE_GITHUB__COM=""
JIRA_API_TOKEN=''
JIRA_API_HOSTNAME=''
# git config email - <first>.<last>@<company>.com
EMAIL=''
WORK_HOSTNAME=''
