---
- name: Create newsboat directory
  ansible.builtin.file:
    path: "{{ ansible_facts['env'].HOME }}/.newsboat"
    state: directory
    mode: "0755"

- name: Create newsraft directory
  ansible.builtin.file:
    path: "{{ ansible_facts['env'].HOME }}/.config/newsraft"
    state: directory
    mode: "0755"

- name: Check if op is available
  ansible.builtin.command:
    cmd: which op
  register: op_check
  changed_when: false
  failed_when: false

- name: Fetch and install feed URLs from 1Password
  when: op_check.rc == 0
  block:
    - name: Fetch newsboat URLs from 1Password
      ansible.builtin.shell:
        cmd: op item get newsboat_urls --fields=notesPlain | sed 's/"//g'
      register: newsboat_urls
      changed_when: false

    - name: Write newsboat URLs
      ansible.builtin.copy:
        content: "{{ newsboat_urls.stdout }}"
        dest: "{{ ansible_facts['env'].HOME }}/.newsboat/urls"
        mode: "0644"

    - name: Fetch newsraft URLs from 1Password
      ansible.builtin.shell:
        cmd: op item get newsraft_urls --fields=notesPlain | sed 's/"//g'
      register: newsraft_urls
      changed_when: false

    - name: Write newsraft URLs
      ansible.builtin.copy:
        content: "{{ newsraft_urls.stdout }}"
        dest: "{{ ansible_facts['env'].HOME }}/.config/newsraft/feeds"
        mode: "0644"
