function report_cleanup -d "Removes autogenerated .css files that get created when generating reports"
    rm -rf .sass-cache
    rm app/assets/stylesheets/application.css
    rm app/assets/stylesheets/reports.css
end
