#!/bin/sh

gitleaks protect -v --staged
exitCode=$?

if [ $exitCode -eq 1 ]; then
  echo "Warning: gitleaks has detected sensitive information in your changes."
  echo "To disable the gitleaks precommit hook run the following command:"
  echo ""
  echo "    git config hooks.gitleaks false"
  exit 1
fi
