# move focus
map ctrl+left neighboring_window left
map ctrl+down neighboring_window down

# move window
map shift+left move_window right
map shift+down move_window up

# switch to previously active window
map ctrl+p nth_window -1

# moves the window into a new OS window
map ctrl+f2 detach_window
# moves the window into a new tab
map ctrl+f3 detach_window new-tab
# moves the window into the previously active tab
map ctrl+f3 detach_window tab-prev
# moves the window into the tab at the left of the active tab
map ctrl+f3 detach_window tab-left
# asks which tab to move the window into
map ctrl+f4 detach_window ask

# moves the tab into a new OS window
map ctrl+f2 detach_tab
# asks which OS Window to move the tab into
map ctrl+f4 detach_tab ask

map f9 close_other_windows_in_tab

# open file in nvim at line number
map ctrl+g kitten hints --type=linenum --linenum-action=tab nvim +{line} {path}
