[general]
# https://github.com/alacritty/alacritty/issues/5999
import = [
  # "themes/themes/gruvbox_light.toml"
  # "themes/themes/gruvbox_dark.toml"
  "theme.toml"
]

[env]
WINIT_X11_SCALE_FACTOR = "1.0"
EDITOR = "nvim"

[window]
decorations = "buttonless"
# opacity = 0.8

[font]
size = 10

  [font.bold]
  family = "JetBrains Mono Nerd Font"
  style = "Heavy"

  [font.bold_italic]
  family = "JetBrains Mono Nerd Font"
  style = "Heavy Italic"

  [font.italic]
  family = "JetBrains Mono Nerd Font"
  style = "Medium Italic"

  [font.normal]
  family = "JetBrains Mono Nerd Font"
  style = "Medium"

[terminal.shell]
  program = "fish"

