set -g prefix C-a
unbind C-b

# set the delay between prefix and command
set -s escape-time 1

# Set the base index of windows to 1 instead of 0
set -g base-index 1

# Set the base index for panes to 1 instead of 0
setw -g pane-base-index 1
