# https://themes.halloy.chat/
# NOTE: This must be before any other configuration
theme = "gruvbox"
# Halloy config.
#
# For a complete list of available options,
# please visit https://halloy.squidowl.org/configuration/index.html

# TODO: Set up soju/znc/glowing bear bouncer

# THEME
# https://github.com/squidowl/halloy/tree/2025.2/book/src/configuration/themes

#          ╭──────────────────────────────────────────────────────────╮
#          │                         SERVERS                          │
#          ╰──────────────────────────────────────────────────────────╯
# In order of popularity...
# https://netsplit.de/networks/top100.php

# NOTE: Accounts registered after March 2024 and have verified email address automatically have cloak assigned
# https://libera.chat/guides/cloaks#generic-user-cloaks
[servers.liberachat]
server = "irc.libera.chat"
channels = ["#halloy", "#gemini"]
nickname = "swmm"
alt_nicks = ["swmm0", "swmm1", "swmm2"]
# username = ""
# realname = ""

[servers.liberachat.sasl.external]
cert = "/home/drew/certs/nick.pem"

# NOTE: Initial setup:
# /msg NickServ REGISTER password email
# https://www.oftc.net/Services/#register-your-account
[servers.oftc]
server = "irc.oftc.net"
channels = ["#oftc"]
nickname = "swmm"
alt_nicks = ["swmm0", "swmm1", "swmm2"]
# username = ""
# realname = ""
on_connect = ["/msg NickServ SET CLOAK ON"]

# https://www.oftc.net/NickServ/CertFP/#automatically-identifying-using-ssl--certfp
[servers.oftc.sasl.external]
cert = "/home/drew/certs/nick.pem"

[servers.hackint]
server = "irc.hackint.org"
channels = ["#hackint", "#nixos"]
nickname = "swmm"
alt_nicks = ["swmm0", "swmm1", "swmm2"]
# username = ""
# realname = ""
on_connect = ["/msg NickServ SET CLOAK ON"]

[servers.hackint.sasl.external]
cert = "/home/drew/certs/nick.pem"

[servers.rizon]
server = "irc.rizon.net"
channels = ["#chat"]
nickname = "swmm"
alt_nicks = ["swmm0", "swmm1", "swmm2"]
# username = ""
# realname = ""
# on_connect = ["/msg NickServ SET CLOAK ON"]

[servers.rizon.sasl.external]
cert = "/home/drew/certs/nick.pem"

[servers.tildechat]
server = "irc.tilde.chat"
# https://tilde.chat/stats/
channels = ["#gemini"]
nickname = "swmm"
alt_nicks = ["swmm0", "swmm1", "swmm2"]
# username = ""
# realname = ""
# on_connect = ["/msg NickServ SET CLOAK ON"]

[servers.tildechat.sasl.external]
cert = "/home/drew/certs/nick.pem"

# ACTIONS
# https://github.com/squidowl/halloy/blob/2025.2/book/src/configuration/sidebar.md
[sidebar]
buffer_action = "replace-pane"
buffer_focused_action = "close-pane"

# https://github.com/squidowl/halloy/blob/2025.2/book/src/configuration/buffer.md
[buffer]
default_action = "replace-pane"

#          ╭──────────────────────────────────────────────────────────╮
#          │                         KEYBOARD                         │
#          ╰──────────────────────────────────────────────────────────╯
# https://github.com/squidowl/halloy/blob/2025.2/book/src/configuration/keyboard.md
# TODO: Figure out why alt key seems to be getting hijacked
[keyboard]
move_up = "alt+k"
move_down = "alt+j"
move_left = "alt+h"
move_right = "alt+l"

#          ╭──────────────────────────────────────────────────────────╮
#          │                           FONT                           │
#          ╰──────────────────────────────────────────────────────────╯
[font]
family = "JetBrainsMono Nerd Font"
