# https://themes.halloy.chat/
# NOTE: This must be before any other configuration
theme = "gruvbox"
# Halloy config.
#
# For a complete list of available options,
# please visit https://halloy.squidowl.org/configuration/index.html

# TODO: Set up soju/znc/glowing bear bouncer

# THEME
# https://github.com/squidowl/halloy/tree/2025.2/book/src/configuration/themes

#          ╭──────────────────────────────────────────────────────────╮
#          │                         SERVERS                          │
#          ╰──────────────────────────────────────────────────────────╯
# In order of popularity...
# https://netsplit.de/networks/top100.php

# NOTE: Accounts registered after March 2024 and have verified email address automatically have cloak assigned
# https://libera.chat/guides/cloaks#generic-user-cloaks
[servers.liberachat]
server = "irc.libera.chat"
# Channels: https://netsplit.de/channels/?net=Libera.Chat
channels = [
  # "#linux",
  # "#archlinux",
  # "#archlinux-security",
  "#libera",
  # "#security",
  # "#debian",
  # "#c",
  # "#git",
  # "#postgresql",
  # "#go-nuts",
  # "#freebsd",
  # "#freebsd-social",
  # "#openbsd",
  # "#weechat",
  # "#vim",
  # "#wireguard",
  # "#znc",
  # "#docker",
  # "#halloy",
  # "#neovim",
  # "#raspberrypi",
  # "#systemd",
  # "#sway",
  # "#nginx",
  # "#bitcoin",
  # "#monero",
  # "#nextcloud",
  # "#javascript",
  # "#crypto",
  # "#tmux",
  # "#node.js",
  # "#kubernetes",
  # "#gemini",
  # "##politics",
  # "#mediawiki",
  # "#gitlab",
  # "#lua",
  # "#mastodon",
  # "#musicbrainz",
  # "##github",
  # "#typescript",
  # "#neomutt",
  # "#jellyfin",
  # "#restic",
  # "#css",
  # "#music",
  # "##music",
  # "#beets",
  # "#jq",
  # "#grapheneos",
  # "#rubyonrails",
  # "#nyxt",
  # "#pihole",
  # "##books",
  # "#mpd",
  # "#coffee",
  # "#html",
  # "#tor",
  # "#cybersecurity",
  # "#glowing-bear",
  # "#electrum",
  # "#tox",
  # "#wireshark"
]
nickname = "swmm"
alt_nicks = ["swmm0", "swmm1", "swmm2"]
# username = ""
# realname = ""

[servers.liberachat.sasl.external]
cert = "/home/drew/certs/nick.pem"

[servers.undernet]
server = "irc.undernet.org"
channels = [
  "#undernet", 
  "#help", 
  # "#bookz",
  # "#usa",
  # "#btc",
  # "#politics",
  # "#Dallas",
  # "#Monero",
  # "#linux",
  # "#exploit",
  # "#americapolitics",
  # "#House",
  # "#debian",
]
nickname = "swmm"
alt_nicks = ["swmm0", "swmm1", "swmm2"]
# username = ""
# realname = ""

# undernet does not support ssl - why?
port = 6667
use_tls = false

[servers.undernet.sasl.external]
cert = "/home/drew/certs/nick.pem"

# NOTE: Initial setup:
# /msg NickServ REGISTER password email
# https://www.oftc.net/Services/#register-your-account
[servers.oftc]
server = "irc.oftc.net"
channels = [
  "#oftc",
  # "#tor-project",
  # "#tor",
  # "#debian-mentors",
  # "#freedesktop",
  # "#tor-relays",
  # "#vbox",
  "#help",
  # "#i2p"
]
nickname = "swmm"
alt_nicks = ["swmm0", "swmm1", "swmm2"]
# username = ""
# realname = ""
on_connect = ["/msg NickServ SET CLOAK ON"]

# https://www.oftc.net/NickServ/CertFP/#automatically-identifying-using-ssl--certfp
[servers.oftc.sasl.external]
cert = "/home/drew/certs/nick.pem"

# NOTE: Services: https://hackint.org/services
[servers.hackint]
server = "irc.hackint.org"
channels = [
  "#hackint",
  "#nixos",
  # "#dn42",
  # "#webroasting",
  # "#codearchiver",
  # "#hackernews",
  # "#infosec",
  # "#oss-security",
  # "#music",
]
nickname = "swmm"
alt_nicks = ["swmm0", "swmm1", "swmm2"]
# username = ""
# realname = ""

[servers.hackint.sasl.external]
cert = "/home/drew/certs/nick.pem"

# TODO: Set vhost: https://wiki.rizon.net/index.php?title=VHost
[servers.rizon]
server = "irc.rizon.net"
channels = [
  "#chat",
  "#randommusic",
]
nickname = "swmm"
alt_nicks = ["swmm0", "swmm1", "swmm2"]
# username = ""
# realname = ""
# on_connect = ["/msg NickServ SET CLOAK ON"]

[servers.rizon.sasl.external]
cert = "/home/drew/certs/nick.pem"

# NOTE: Requesting vhost/cloak: https://tilde.wiki/Tilde.chat/HostServ
[servers.tildechat]
server = "irc.tilde.chat"
# https://tilde.chat/stats/
channels = [
  "#meta", 
  "#helpdesk", 
  "#gemini",
  # "#selfhosting",
  # "#linux",
  # "#offthegrid",
  # "#books",
]
nickname = "swmm"
alt_nicks = ["swmm0", "swmm1", "swmm2"]
# username = ""
# realname = ""
# on_connect = ["/msg NickServ SET HIDE USERMASK ON"]

[servers.tildechat.sasl.external]
cert = "/home/drew/certs/nick.pem"

# ACTIONS
# https://github.com/squidowl/halloy/blob/2025.2/book/src/configuration/sidebar.md
[sidebar]
buffer_action = "replace-pane"
buffer_focused_action = "close-pane"

# https://github.com/squidowl/halloy/blob/2025.2/book/src/configuration/buffer.md
[buffer]
default_action = "replace-pane"

#          ╭──────────────────────────────────────────────────────────╮
#          │                         KEYBOARD                         │
#          ╰──────────────────────────────────────────────────────────╯
# https://github.com/squidowl/halloy/blob/2025.2/book/src/configuration/keyboard.md
# TODO: Figure out why alt key seems to be getting hijacked
[keyboard]
move_up = "alt+k"
move_down = "alt+j"
move_left = "alt+h"
move_right = "alt+l"

#          ╭──────────────────────────────────────────────────────────╮
#          │                           FONT                           │
#          ╰──────────────────────────────────────────────────────────╯
[font]
family = "JetBrainsMono Nerd Font"
